name: checklist
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


  get:
  get_storage:
  dio:
  cached_network_image:
  signature:

  drift:
  sqlite3_flutter_libs:
  path_provider:
  path:
  encrypt:
  fl_downloader:
  url_launcher:

  i2iutils:
    path: ../i2iutils

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  drift_dev:
  build_runner: # cmd for run : flutter pub run build_runner build


# The following section is specific to Flutter packages.
flutter:

